import type { WorkspaceSignal } from "./types";

export const workspaceSignals: WorkspaceSignal[] = [
  {
    id: "design-system",
    label: "Design System Refresh",
    symbol: "UI-01",
    focusArea: "Experience",
    value: 84.5,
    dayChangePct: 2.4,
    monthChangePct: 7.1,
    signal: "Accelerating",
    note: "Component adoption is climbing quickly now that primitives and docs are aligned.",
  },
  {
    id: "auth-boundary",
    label: "Auth Boundary Hardening",
    symbol: "PL-07",
    focusArea: "Foundation",
    value: 68.2,
    dayChangePct: -0.8,
    monthChangePct: 2.1,
    signal: "Watch",
    note: "Permissions and session flows need another pass before downstream teams can move faster.",
  },
  {
    id: "product-insights",
    label: "Product Insights Pipeline",
    symbol: "PD-12",
    focusArea: "Product",
    value: 77.6,
    dayChangePct: 1.3,
    monthChangePct: 4.4,
    signal: "Steady",
    note: "Reporting coverage is good enough to support prioritization, but instrumentation still has gaps.",
  },
  {
    id: "growth-loop",
    label: "Self-Serve Onboarding",
    symbol: "GR-03",
    focusArea: "Growth",
    value: 63.1,
    dayChangePct: 3.1,
    monthChangePct: 6.2,
    signal: "Accelerating",
    note: "Activation work is paying off, and the next bottleneck has become clearer.",
  },
  {
    id: "ops-automation",
    label: "Workflow Automation",
    symbol: "OP-05",
    focusArea: "Operations",
    value: 71.4,
    dayChangePct: -1.6,
    monthChangePct: 1.7,
    signal: "Steady",
    note: "The operating baseline is improving, but recurring manual steps still slow releases down.",
  },
  {
    id: "developer-experience",
    label: "Developer Experience",
    symbol: "DX-09",
    focusArea: "Foundation",
    value: 79.9,
    dayChangePct: 1.9,
    monthChangePct: 5.6,
    signal: "Accelerating",
    note: "Tooling friction is dropping, which is making every other focus area easier to ship.",
  },
];
