import type { MarketInstrument } from "./types";

export const marketWatchlist: MarketInstrument[] = [
  {
    id: "ust-2y",
    label: "US 2Y Treasury",
    symbol: "UST2Y",
    assetClass: "Rates",
    price: 4.18,
    dayChangePct: -0.42,
    monthChangePct: -1.18,
    signal: "Cooling",
    thesis: "Front-end yields are easing as the market prices softer inflation prints.",
  },
  {
    id: "ust-10y",
    label: "US 10Y Treasury",
    symbol: "UST10Y",
    assetClass: "Rates",
    price: 4.03,
    dayChangePct: -0.19,
    monthChangePct: -0.74,
    signal: "Balanced",
    thesis: "Long duration is stabilizing, but term premium still argues for restraint.",
  },
  {
    id: "dxy",
    label: "Dollar Index",
    symbol: "DXY",
    assetClass: "FX",
    price: 103.74,
    dayChangePct: 0.31,
    monthChangePct: 0.88,
    signal: "Balanced",
    thesis: "The dollar is firm again as relative growth surprises lean back toward the US.",
  },
  {
    id: "ig-spread",
    label: "US IG Credit Spread",
    symbol: "CDX-IG",
    assetClass: "Credit",
    price: 58.4,
    dayChangePct: -0.26,
    monthChangePct: -0.64,
    signal: "Balanced",
    thesis: "Spreads remain contained, keeping carry attractive for patient balance sheets.",
  },
  {
    id: "brent",
    label: "Brent Crude",
    symbol: "BRN",
    assetClass: "Commodities",
    price: 84.1,
    dayChangePct: 1.42,
    monthChangePct: 4.86,
    signal: "Heating",
    thesis: "Supply discipline is reasserting itself faster than demand is fading.",
  },
  {
    id: "global-equity",
    label: "Global Quality Equity",
    symbol: "ACWI-Q",
    assetClass: "Equities",
    price: 146.8,
    dayChangePct: 0.84,
    monthChangePct: 3.91,
    signal: "Heating",
    thesis:
      "Quality-led equity breadth is improving, but it still needs real earnings follow-through.",
  },
];
